controllers:
  - path: /var/www/payment_system/controllers
    method_prefix: action
    namespace: app\controllers

files:
  - /var/www/payment_system/views/private/materials

urls:
  - /var/www/payment_system/composer.json

roles:
  - Администратор
  - Преподаватель
  - Слушатель
  - Гость

default_role: Гость

persistent_storage: postgresql
cache_storage: redis

postgresql:
  dns: pgsql:host=/var/run/postgresql;port=5432;dbname=edu
  user: avtomonov
  password: password

redis:
  socket: /var/run/redis/redis.sock

filter_label: aclessFilter

accless_label: aclessMethod
