controllers:
  - path: /var/www/payment_system/controllers
    method_prefix: action
    namespace: app\controllers

files:
  - /var/www/payment_system/views/private/materials

urls:
  - /var/www/payment_system/composer.json

roles:
  - Администратор
  - Преподаватель
  - Слушатель
  - Гость