controllers:
  - path: /var/www/payment_system/controllers
    method_prefix: action
    namespace: app\controllers

files:
  - /var/www/payment_system/view/private/materials

urls:
  - /var/www/payment_system/composer.json